#!/usr/bin/env bash
# Every 1st line of a bash script starts with #! followed by the shell that should run the script

source ../../ENVIRONMENT_VARIABLES		# Load variables/code present in a different file
echo "BIN_DIR:" $BIN_DIR			# echo -> print a string to the stdout
echo "PSEUDO_DIR:" $PSEUDO_DIR
echo "TMP_DIR:" $TMP_DIR
echo "Parallel command:" $RUN_COMMAND
echo "Started at: " `date`

SAVE=Etot_vs_vacuum-script.dat
echo -e "# vacuum(Angstrom)   Energy(Ry)" > $SAVE

# Define the reference bulk constants based on your positions
C_ONE_CELL=5.25
# Your coordinate space spans exactly 1.5 bulk unit cells (8 atoms total)
C_BULK_TOTAL=$(echo "scale=9; $C_ONE_CELL * 2" | bc)

for vacuum in 10 15 20; do

    echo "Running calculation for vacuum: ${vacuum} Å"

    IN=GaN_script.scf.in
    OUT=GaN_script.scf.out_${vacuum}

    # 1. Calculate the dynamic C_SLAB for the system using 'bc' (floating-point math)
    C_SLAB=$(echo "scale=9; $C_BULK_TOTAL + $vacuum" | bc)

    # 2. Re-scale the fractional Z-coordinates exactly relative to the new C_SLAB
    Z1=$(echo "scale=9; ($C_ONE_CELL * 0.50) / $C_SLAB" | bc)
    Z2=$(echo "scale=9; ($C_ONE_CELL * 0.376382) / $C_SLAB" | bc)
    Z3=$(echo "scale=9; ($C_ONE_CELL * 0.876382) / $C_SLAB" | bc)
    Z4=$(echo "scale=9; ($C_ONE_CELL * 1.00) / $C_SLAB" | bc)
    Z5=$(echo "scale=9; ($C_ONE_CELL * 1.50) / $C_SLAB" | bc)
    Z6=$(echo "scale=9; ($C_ONE_CELL * 1.376382) / $C_SLAB" | bc)
    Z7=$(echo "scale=9; ($C_ONE_CELL * 1.876382) / $C_SLAB" | bc)

    # self-consistent calculation input generation
    cat > $IN << EOF
&CONTROL
    calculation       = 'scf'
    restart_mode      = 'from_scratch'
    prefix            = 'GaN'
    tstress           = .true.
    tprnfor           = .true.
    pseudo_dir        = "$PSEUDO_DIR"
    outdir            = "$TMP_DIR"
    verbosity         = 'high'
    disk_io           = 'minimal'
    wf_collect        = .true.
/
&SYSTEM
    ibrav     = 4,
    A         = 3.22,
    C         = $C_SLAB,
    nat       = 8,
    ntyp      = 2,
    ecutwfc   = 70,
    ecutrho   = 700,
    nbnd      = 40,  
/
&ELECTRONS
    conv_thr    = 1.D-8,
    mixing_beta = 0.7D0,
/
ATOMIC_SPECIES
 Ga  69.723  Ga.pbe-dn-kjpaw_psl.1.0.0.UPF
 N   14.007  N.pbe-n-kjpaw_psl.1.0.0.UPF
ATOMIC_POSITIONS {crystal}
 Ga 0.333333333 0.666666666 0.000000000 0 0 0
 Ga 0.666666666 0.333333333 $Z1 0 0 0
 N  0.333333333 0.666666666 $Z2 0 0 0
 N  0.666666666 0.333333333 $Z3 0 0 0
 Ga 0.333333333 0.666666666 $Z4 0 0 0
 Ga 0.666666666 0.333333333 $Z5 0 0 0
 N  0.333333333 0.666666666 $Z6 0 0 0
 N  0.666666666 0.333333333 $Z7 0 0 0
K_POINTS {automatic}
4 4 1 1 1 1
EOF

    echo -e "\tStart: " `date`
    # Fixed the hidden space syntax error in the parallel execution line
    $RUN_COMMAND $BIN_DIR/pw.x < $IN > $OUT
    echo -e "\tEnd: " `date`

    # Extract the total energy (the line containing '!') safely using awk
    ENERGY=$(grep '!' $OUT | awk '{print $5}')

    # Save to your output file cleanly
    echo -e "$vacuum\t\t$ENERGY" >> $SAVE

done
echo "Run completed at: " `date`

exit
