#!/usr/bin/env bash

SAVE=Etot_vs_kgrid-script.dat
SAVE0="${SAVE}0"
SAVE1="${SAVE}1"

# Reference energy: last row of the unshifted series (densest grid)
EREF=$(tail -n 1 $SAVE0 | awk '{print $4}')
NAT=4

echo "Reference energy (densest 000 grid): $EREF Ry"

cat > plot-script.gnu <<EOF
#!/usr/bin/gnuplot
set term x11 enhanced

set xlabel "N (NxNxM mesh, M = ceil(0.614 N))"
set ylabel "E_{tot} (Ry)"
set key bottom right
set grid

plot \
	'$SAVE0'  u 1:4 w lp pt 7 lw 2  lc rgb "black" title "E vs NxNxM 000",\
	'$SAVE0'  u 1:4:3 w labels offset char 1,1 notitle,\
	'$SAVE1'  u 1:4 w lp pt 7 lw 2  lc rgb "red" title "E vs NxNxM 111",\
	'$SAVE1'  u 1:4:3 w labels offset char 1,-1 notitle,\
	$EREF+(0.001*$NAT) w l lt 1 dt 2 lc "green" t "+1 mRy/atom",\
	$EREF-(0.001*$NAT) w l lt 1 dt 2 lc "green" t "-1 mRy/atom"

pause -1

set term pdfcairo enhanced
set output "${SAVE}.pdf"
replot

set term pngcairo enhanced
set output "${SAVE}.png"
replot
EOF

gnuplot plot-script.gnu

exit
