#!/usr/bin/env bash
#Every 1st line of a bas script start with #! followed by the shell that should run the script

source ../../ENVIRONMENT_VARIABLES		#Load variables/code present in a different file
echo "BIN_DIR:" $BIN_DIR			#echo -> print a string to the stdout
						#$NAME -> recal the value of a variable of name NAME
echo "PSEUDO_DIR:" $PSEUDO_DIR
echo "TMP_DIR:" $TMP_DIR
echo "Parallel command:" $RUN_COMMAND
echo "Started at: " `date`

SAVE=Etot_vs_kgrid-script.dat
SAVE0="${SAVE}0"
SAVE1="${SAVE}1"

echo -e "# N (NxNxM 000 grid, M=ceil(0.614*N)) \tM \tNKTOT \tenergy(Ry)" > $SAVE0
echo -e "# N (NxNxM 111 grid, M=ceil(0.614*N)) \tM \tNKTOT \tenergy(Ry)" > $SAVE1

for offset in 1 0; do
for grid in 2 3 4 5 6 7 8 9; do

# Third component: 0.614*N rounded UP to the nearest integer 
gridz=$(awk -v n="$grid" 'BEGIN{ v = 0.614*n; m = int(v); if (v > m) m = m + 1; if (m < 1) m = 1; print m }')

klist="$grid $grid $gridz $offset $offset $offset"
echo "k-grid: $klist"

IN=GaN_script.scf.in
OUT=GaN_script.scf.out_k${grid}x${grid}x${gridz}_${offset}

# self-consistent calculation
cat > $IN << EOF

&CONTROL
    calculation       = 'scf'
    restart_mode      = 'from_scratch'
    prefix            = 'GaN'
    tstress           = .true.
    tprnfor           = .true.
    pseudo_dir        = "$PSEUDO_DIR"
    outdir            = "$TMP_DIR"
    verbosity         = 'high'
    disk_io = 'minimal'
    wf_collect        = .true.
/
&SYSTEM
  ibrav     = 4,
  A = 3.180,
  C = 5.180,
  nat       = 4,
  ntyp      = 2,
  ecutwfc   = 70,
  ecutrho   = 700,
  nbnd      = 22,
/
&ELECTRONS
  conv_thr    = 1.D-8,
  mixing_beta = 0.7D0	,
/
ATOMIC_SPECIES
 Ga  69.723  Ga.pbe-dn-kjpaw_psl.1.0.0.UPF
 N    14.007 N.pbe-n-kjpaw_psl.1.0.0.UPF
ATOMIC_POSITIONS {crystal}
 Ga 0.333333333 0.666666666 0.00 0 0 0
 Ga 0.666666666 0.333333333 0.50 0 0 0
 N 0.333333333 0.666666666 0.375 0 0 1
 N 0.666666666 0.333333333 0.875 0 0 1
K_POINTS {automatic}
$klist
EOF

echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`

ENERGY=`grep -F '!' $OUT | tail -n 1 | awk '{print $5}'`
KPOINTS=`grep -m 1 'number of k points' $OUT | awk '{print $5}'`

echo -e "$grid\t\t$gridz\t\t$KPOINTS\t\t$ENERGY" >> $SAVE${offset}

done
done

echo "Run completed at: " `date`
exit
