#!/usr/bin/env bash
#Every 1st line of a bas script start with #! followed by the shell that should run the script

source ../../ENVIRONMENT_VARIABLES		#Load variables/code present in a different file
echo "BIN_DIR:" $BIN_DIR			#echo -> print a string to the stdout
						#$NAME -> recal the value of a variable of name NAME
echo "PSEUDO_DIR:" $PSEUDO_DIR
echo "TMP_DIR:" $TMP_DIR
echo "Parallel command:" $RUN_COMMAND
echo "Started at: " `date`

# Prepare the files to be plotted
SAVE=Etot_vs_Ecut-script.dat				#NAME=something assign a variable of name NAME and value something (can be a string ora  number)
						#!!!!!! There must be no spaces when assigning variable
						#Use "... ..." for a string with spaces
echo -e "# Ecut(Ry)\tEnergy(Ry)" > $SAVE	# COMMAND > NAME  write the stdout of the command COMMAND into the file NAME
						#Create the file if it does not exist
						#Overwrite the file it exist
						#Use >> to append at the end of the file

# Loop over cutoff energies
for ecut in 20 30 40 50 60 70 80 90 100 110 120; do		#for NAME in LIST; do ... done
					#cicle the variable NAME in a list of elements

IN=GaN_script.scf.in
OUT=GaN_script.scf.out_Ecut$ecut
						#<<DELIM  ... DELIM   defines a block of text
						#Will still resolve variables values using $NAME
						#cat NAME/TEXT   read a file or string/block of text and print it into the stdout
# self-consistent calculation
cat > $IN << EOF

&CONTROL
    calculation       = 'scf'
    restart_mode      = 'from_scratch'
    prefix            = 'GaN'
    tstress           = .true.
    tprnfor           = .true.
    pseudo_dir        = "$PSEUDO_DIR"
    outdir            = "$TMP_DIR"
    verbosity         = 'high'
    disk_io = 'minimal'
    wf_collect        = .true.
/
&SYSTEM
  ibrav     = 4,
  A = 3.180,
  C = 5.180,
  nat       = 4,
  ntyp      = 2,
  ecutwfc   = $ecut,
  ecutrho   = $((ecut*10)),
  nbnd      = 22,
/
&ELECTRONS
  conv_thr    = 1.D-8,
  mixing_beta = 0.7D0	,
/
ATOMIC_SPECIES
 Ga  69.723  Ga.pbe-dn-kjpaw_psl.1.0.0.UPF
 N    14.007 N.pbe-n-kjpaw_psl.1.0.0.UPF
ATOMIC_POSITIONS {crystal}
 Ga 0.66 0.33 0.875
 Ga 0.33 0.66 0.375
 N 0.33 0.66 0.00
 N 0.66 0.33 0.50
K_POINTS {automatic}
4 4 4 1 1 1
EOF

echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`

ENERGY=`cat $OUT | grep ! | tr -dc '0-9,-.'`		#COMMAND1 | COMMAND2   pipe stdout of COMMAND1 into the stdin of COMMAND2
							#grep TEXT   look for every line containing the text TEXT and print it in the stdout
							#tr -dc LIST  (delete complementary)  deletes every character that is not present 
							#in the list LIST
echo -e "$ecut\t\t$ENERGY" >> $SAVE

done    # end of main loop over cutoff energy

echo "Run completed at: " `date`

